name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker Version
        run: docker --version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Start PostgreSQL
        run: |
          docker run --name postgres -p 5432:5432 -e POSTGRES_DB=shorteer_url_api -e POSTGRES_USER=postgres -d postgres:latest
          # Wait for PostgreSQL to initialize
          sleep 10

      - name: Run database migrations
        run:
          alembic upgrade head
          
      - name: Run FastAPI application
        run: |
          # Start FastAPI application after database migrations
          source venv/bin/activate
          uvicorn app.main:app --host 0.0.0.0 --port 8000
        # Wait for the application to start
        timeout-minutes: 2
