name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    env:
      DATABASE_URL: postgresql://postgres@localhost:5432/shorteer_url_api
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker Version
        run: docker --version

      - name: Start PostgreSQL
        run: |
          docker run --name postgres -p 5432:5432 -e POSTGRES_DB=shorteer_url_api -e POSTGRES_USER=postgres -d postgres:latest
          # Wait for PostgreSQL to initialize (increase sleep time if needed)
          sleep 10
          # Check container logs for debugging
          docker logs postgres

      - name: Verify Connection
        run: |
          # Test database connection
          docker exec postgres psql -U postgres shorteer_url_api -c "SELECT 1" || exit 1
        
        

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database migrations
        run: |
          alembic upgrade head
