name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: shorteer_url_api
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to initialize
        run: |
          sleep 10
          docker ps -a
          docker logs postgres

      - name: Verify PostgreSQL Connection
        run: |
          docker exec postgres psql -U postgres shorteer_url_api -c "SELECT 1" || exit 1

      - name: Run database migrations
        run: |
          alembic upgrade head
