name: CI

on:
  push:
    branches: [ master ]  # Change to your branch(es) if needed

jobs:
  build:
    runs-on: ubuntu-latest  # Adjust OS as needed

    steps:
      - uses: actions/checkout@v3  # Checkout your code

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requirements.txt  # Replace with your requirements file

      - name: Run migrations
        env:
          DATABASE_URL: postgresql://postgres@localhost:5432/shorteer_url_api
        run: |
          alembic upgrade head

