name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
      
    env:
      DATABASE_URL: postgresql://postgres@localhost:5432/shorteer_url_api

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get --yes install gcc python3-dev libpq-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start PostgreSQL
        uses: docker://postgres:latest
        with:
          env:
          POSTGRES_DB: shorteer_url_api
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Run database migrations
        run: alembic upgrade head
        
      - name: Run FastAPI application
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000
