name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    env:
      DATABASE_URL: postgresql://postgres@localhost:5432/shorteer_url_api

    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get --yes install gcc python3-dev libpq-dev
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database migrations
        run: alembic upgrade head
        
      - name: Run FastAPI application
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # Set up environment variables for database connection
          export DATABASE_URL= ${{secrets.DATABASE_URL}}
          uvicorn app.main:app --host 0.0.0.0 --port 8000