name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up PostgreSQL
      uses: docker-compose-action@v1
      with:
        compose-file: docker-compose.ci.yml

    - name: Run database migrations
      run: alembic upgrade head

    - name: Tear down PostgreSQL
      uses: docker-compose-action@v1
      with:
        compose-file: docker-compose.ci.yml
        down-flags: --volumes
