name: Run FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  run_app:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run FastAPI application
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000
      
      - name: Run tests
        run : |
          pytest app/testclient.py
