name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run database migrations
        run:
          source venv/bin/activate
          alembic upgrade head
          
      - name: Run FastAPI application
        run: |
          # Start FastAPI application after database migrations
          uvicorn app.main:app --host 0.0.0.0 --port 8000
        # Wait for the application to start
        timeout-minutes: 2
